### ISSUE TITLE
require external module

### ISSUE THREAD

**Issue by kurokirasama** [MageLuingil/tasker-commonjs#1]
Hello, i find this very useful, so thanks!!

I'm trying to use [evernote api](https://github.com/evernote/evernote-sdk-js), and i have the following directory structure:
/sdcard/Tasker/scripts/nodejs
 ├─ node_modules/
 │  └─ evernote/
 ├─ tasker-commonjs/
 │  └─ require.js
 ├─ ever.js

I have %CommonJS variable set to `/storage/emulated/0/Tasker/scripts/nodejs/tasker-commonjs/require.js` and %JS_PATH to `/storage/emulated/0/Tasker/scripts/nodejs`

I'm running the javascript with

```
Path: Tasker/scripts/nodejs/ever.js
Library: %CommonJS
```

But i got: `Module not found` error.

Please help.

**Comment by MageLuingil** [comment]
It looks like the `oauth` module used by evernote uses several node.js modules (crypto, http, url, and some others) which aren't available in Tasker's js implementation.  Even if you find a browser-compatible oauth library with the same interface as ciaranj/node-oauth, it still might not work since there's one file in Evernote's module that uses node-specific modules as well.  Unfortunately, the evernote API may not work in Tasker.

That said, it looks like I do need to update the error messaging to be more helpful.  I'll push that in an update soon (probably tomorrow when I have some time).

**Comment by kurokirasama** [comment]
Ok. But this is still the issue if I'm not using oauth. I'm using the token authorization. Or is it the same?

**Comment by MageLuingil** [comment]
It really depends on whether Evernote built their JS API to fail gracefully without oauth (or node.js).  They require the oauth module in their client.js file, but the module may not be used at all if you're using a different auth method.  You could try making an empty module named "oauth" so the require works and the code can continue.

I meant to do some testing of my own on this over the weekend, but I didn't get to it.  I did update the require library to tell you which module failed to load when it errors, so that may help you debug your code, at least.  Try updating to the latest version and see which module is failing to load.

**Comment by kurokirasama** [comment]
I got `Evernote not found`

**Comment by MageLuingil** [comment]
It looks like the case of the module you're trying to include is different from the folder structure ("Evernote" vs "evernote").  The module loader is case-sensitive - have you tried loading it with a lowercase 'e'?

**Comment by kurokirasama** [comment]
Sorry, it was `evernote not found`

**Comment by MageLuingil** [comment]
If it can't find the evernote module, then most likely either the module itself isn't valid (i.e. if the evernote module was installed incorrectly), or the JS_PATH isn't correct.

I just ran a quick test on my phone by doing the following:
* Installed evernote to a directory on my computer using `npm install evernote`
* Copied the resulting node_modules directory to my phone's JS_PATH
* Added an empty file named "oauth.js" to my phone's JS_PATH (to bypass loading the oauth library)
* Added an action file named "evernote-test.js" with the following:
```
try {
	const evernote = require('evernote');
} catch (e) {
	flash('Error: ' + e.message);
}
```

Following these steps, the evernote library seems to have loaded correctly, but I got the message `Module "https" not found`.  Evernote seems using `https` (which is a core node.js library) as part of it's http transport library.

I'm still not sure why the evernote library itself is failing to load on your device.  However, since the evernote API relies on node.js libraries to work, I'm afraid it probably won't work in Tasker -- at least not with out a large amount of modification or shimming node functions.

**Comment by kurokirasama** [comment]
Ok. First, I had git cloned the repo instead of mom-installed it, now it recognize evernote module.
I followed your steps but I couldn't reproduce your results. Instead, I got `oauth module not found`. I installed it (it came with the Evernote module) and I got `crypto module not found`. I tried installing it, but it's deprecated since is now a built in module. Do you now where can I get it?

**Comment by MageLuingil** [comment]
`crypto` is also a node.js module.  I didn't get that error because I bypassed loading `oauth` by creating my own (empty) oauth module in JS_PATH.  It really looks like evernote's API wasn't designed to work in a webview.

**Comment by MageLuingil** [comment]
I'm closing this issue since it's not something I can fix in the `require()` implementation.
